obj-$(CONFIG_PANEL_GENERIC_DPI) += panel-generic-dpi.o
obj-$(CONFIG_PANEL_LGPHILIPS_LB035Q02) += panel-lgphilips-lb035q02.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o
obj-$(CONFIG_PANEL_NEC_NL8048HL11_01B) += panel-nec-nl8048hl11-01b.o
obj-$(CONFIG_PANEL_S6E8AA0) += panel-s6e8aa0.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
obj-$(CONFIG_PANEL_TPO_TD043MTEA1) += panel-tpo-td043mtea1.o
obj-$(CONFIG_PANEL_ACX565AKM) += panel-acx565akm.o

obj-$(CONFIG_PANEL_TC358765) += panel-tc358765.o
obj-$(CONFIG_PANEL_LD089WU1) += panel-ld089wu1.o
obj-$(CONFIG_PANEL_LTN) += panel-ltn.o
obj-$(CONFIG_PANEL_TC358765_BOXER) += panel-tc358765-boxer.o
obj-$(CONFIG_PANEL_BOXER) += panel-boxer.o
obj-$(CONFIG_PANEL_AUO) += panel-auo.o
obj-$(CONFIG_PANEL_HYDIS) += panel-hydis.o
obj-$(CONFIG_PANEL_NOVATEK) += panel-novatek.o
obj-$(CONFIG_PANEL_ORISE) += panel-orise.o
